/*
GET STATISTICS FROM THE ALT TABLE WHERE ACCOUNTS WHERE DISCHARGED,
NEED STATS ON THE FOLLOWING:
1. ACCT_TYPE
2. PT_TYPE, AND
3. FC

THIS WILL ALLOW US TO SEE HOW MANY CLAIMS WE NEED BY GETTING US THE PERCENTAGE
OF DISCHARGES THAT MEET EACH COMBINATION OF ACCT_TYPE:PT_TYPE:FC
*/
WITH CTE AS (
    SELECT ACCT_TYPE,
        PT_TYPE,
        [UNITIZED_IND] = CASE WHEN PT_TYPE IN ('D','N') THEN 'Y' ELSE 'N' END,
        INS1_CD,
        [DISCHARGES] = 1
    FROM SMS.DBO.Pt_Accounting_Reporting_ALT
    WHERE DSCH_DATE >= '2026-01-01'
    AND DSCH_DATE < '2026-06-01'
    AND FC NOT LIKE '[0-9]'
)

SELECT ACCT_TYPE,
    PT_TYPE,
    UNITIZED_IND,
    ACT_PT_TYPE = CASE 
        WHEN ACCT_TYPE = 'IP' 
            THEN 'IP'
        WHEN ACCT_TYPE = 'OP'
            AND UNITIZED_IND = 'N'
            THEN 'OP'
        ELSE 'UN'
        END, 
    INS1_CD,
    DISCHARGES = SUM(DISCHARGES)
FROM CTE AS CTE
GROUP BY ACCT_TYPE,
    PT_TYPE,
    UNITIZED_IND,
    Ins1_Cd;


SELECT TOP 1 INST.Patient_Account_Number,
    INST.PT_NO,
    INST.INS_CD,
    INST.PAYER_ID,
    INST.UNIT_NO,
    INST.SEQ_NO,
    INST.FILE_CREATION_DATE,
    INST.CHARGE_AMOUNT,
    INST.FACILITY_TYPE_CODE,
    INST.FACILITY_CODE,
    INST.FREQUENCY_CODE,
    INST.ADMISSION_TYPE_CODE,
    INST.ADMISSION_SOURCE_CODE,
    INST.PATIENT_STATUS_CODE,
    ALT.FC,
    ALT.Acct_Type,
    ALT.Pt_Type
FROM SMS.dbo.c_INST_tbl AS INST
LEFT JOIN SMS.DBO.Pt_Accounting_Reporting_ALT AS ALT ON INST.PT_NO = ALT.Pt_No 
    AND (
        INST.Unit_NO = ALT.Unit_No
        OR INST.UNIT_NO IS NULL
    )
WHERE EDI_FORMAT = '837';

