SELECT PT_NO,
    UNIT_NO,
    [ADM_DATE] = CAST(ADMIT_DATE AS DATE),
    [DSCH_DATE] = CAST(DSCH_DATE AS DATE),
    [UNIT_DATE] = CAST(UNIT_DATE AS DATE),
    ACTIVE_ARCHIVE,
    FC,
    FC_DESCRIPTION,
    BALANCE, 
    INS_BALANCE,
    PT_BALANCE,
    PT_REPRESENTATIVE,
    PT_REP_DESC,
    OPEN_FC_IND = CASE WHEN FC IN ('2','4','6','8') THEN 1 ELSE 0 END,
    OPEN_REP_IND = CASE WHEN PT_REPRESENTATIVE IN ('721') THEN 1 ELSE 0 END,
    OPEN_FC_WITH_CLOSE_REP_IND = CASE
        WHEN FC IN ('2','4','6','8') 
        AND PT_REPRESENTATIVE IN ('722','744') 
            THEN 1
        ELSE 0
    END,
    CLOSE_FC_WITH_OPEN_REP_IND = CASE
        WHEN FC = '3'
        AND PT_REPRESENTATIVE IN ('721') 
            THEN 1
        ELSE 0
    END,
    OPEN_FC_AND_OPEN_REP_IND = CASE
        WHEN FC IN ('2','4','6','8') 
        AND PT_REPRESENTATIVE IN ('721') 
            THEN 1
        ELSE 0
    END,
    OPEN_FC_OR_OPEN_REP_IND = CASE
        WHEN FC IN ('2','4','6','8') 
        OR PT_REPRESENTATIVE IN ('721') 
            THEN 1
        ELSE 0
    END,
    CLOSE_FC_CLOSE_REP_IND = CASE
        WHEN FC = '3'
        AND PT_REPRESENTATIVE IN ('722','744') 
            THEN 1
        ELSE 0
    END,
    UNITIZED = CASE WHEN UNIT_NO IS NOT NULL THEN 1 ELSE 0 END,
    DISTINCT_ACCOUNT = CASE WHEN ROW_NUMBER() OVER (PARTITION BY PT_NO ORDER BY ADMIT_DATE DESC) = 1 THEN 1 ELSE 0 END,
    UNITIZED_LABEL = CASE WHEN UNIT_NO IS NOT NULL THEN 'Unitized' ELSE 'Non Unitized' END
FROM SMS.DBO.PT_ACCOUNTING_REPORTING_ALT
WHERE (
    FC IN ('1','2','3','4','6','8')
    OR PT_REPRESENTATIVE IN ('721','722','744')
)
AND BALANCE <> 0