/*
***********************************************************************
File: WORKABLE_PRODUCTIVITY.sql

Input Parameters:
	@PRODUCTIVITY_DATE (DATETIME) - The date for productivity data.
	@WORKABLE_DATE (DATE) - The date for workable indicator data.

Tables/Views:
	SMS.dbo.c_productivity_combined
	SMS.dbo.C_WORKABLE_INDICATOR_DETAIL_TBL
	SMS.DBO.Pt_Accounting_Reporting_for_tableau

Creates Table:
	#BASE_POP
	#ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL
	#ACCTS_WORKED_IN_SNAPSHOT_TBL
	#ACCTS_WORKED_TBL
	#ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL
	#ACCT_DOLLARS_IN_SNAPSHOT_TBL
	#ACCTS_DOLLARS_WORKED
	#TEMPA
	#TempDepartments
	#TEMPB
	#TEMPC

Functions:
	TRY_CONVERT

Author: Steven P Sanderson II, MPH

Department: Finance, Revenue Cycle

Purpose/Description:
	This script processes productivity and workable indicator data to generate
	account-level details, including accounts worked and dollars worked, for
	further analysis and reporting.

Revision History:
Date		Version		Description
----		----		----
2018-07-13	v1			Initial Creation
***********************************************************************
*/


DECLARE @PRODUCTIVITY_DATE AS DATETIME;
DECLARE @WORKABLE_DATE AS DATE;

SET @PRODUCTIVITY_DATE = (
	SELECT RRD.report_run_date
	FROM (
	SELECT report_run_date,
		RN = ROW_NUMBER() OVER(
			ORDER BY REPORT_RUN_DATE DESC
		)
	FROM SMS.dbo.c_productivity_combined
	GROUP BY report_run_date
	) AS RRD
	WHERE RRD.RN = 1
);
SET @WORKABLE_DATE = (
	SELECT TOP 1 RRD.REPORT_RUN_DATE
	FROM (
		SELECT TOP 2 REPORT_RUN_DATE
		FROM SMS.dbo.C_WORKABLE_INDICATOR_DETAIL_TBL
		GROUP BY Report_Run_Date
		ORDER BY Report_Run_Date DESC
	) AS RRD
	ORDER BY RRD.Report_Run_Date
);

DROP TABLE IF EXISTS #BASE_POP;
SELECT PT_NO,
	UNIT_NO,
	UNIT_DATE,
	DEPARTMENT_CLEAN,
	WORKABLE_INDICATOR
INTO #BASE_POP
FROM SMS.dbo.C_workable_indicator_detail_tbl
WHERE [FILE] NOT IN ('BAD DEBT')
AND Report_Run_Date = @WORKABLE_DATE;

/* ACCOUNTS WORKED

THERE WILL BE ACCOUTNS THAT ARE WORKED BUT NOT IN THE SNAPSHOT FOR VARIOUS REASONS
FOR EXAMPLE THE BALANCE AT SNAPSHOT TIME IS 0 AND IT IS NOT WORKLISTED.

*/
DROP TABLE IF EXISTS #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL;
SELECT B.PT_NO,
	B.DEPT,
	B.UNIT_DATE,
	B.UNIT,
	ACCTS_WORKED = 1
INTO #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL
FROM #BASE_POP AS A 
RIGHT JOIN SMS.dbo.c_productivity_combined AS B ON A.PT_NO = B.PT_NO
WHERE B.report_run_date = @PRODUCTIVITY_DATE
AND A.PT_NO IS NULL
GROUP BY B.DEPT,
	B.UNIQUE_USER_ID,
	B.FOL_AMT,
	B.UNIQUE_DATE,
	B.PT_NO,
	B.UNIT_DATE,
	B.UNIT;

DROP TABLE IF EXISTS #ACCTS_WORKED_IN_SNAPSHOT_TBL;
SELECT B.PT_NO,
	B.DEPT,
	B.UNIT_DATE,
	B.UNIT,
	ACCTS_WORKED = 1
INTO #ACCTS_WORKED_IN_SNAPSHOT_TBL
FROM #BASE_POP AS A
LEFT JOIN SMS.DBO.c_productivity_combined AS B ON A.PT_NO = B.PT_NO
WHERE B.report_run_date = @PRODUCTIVITY_DATE
GROUP BY B.DEPT,
	B.UNIQUE_USER_ID,
	B.FOL_AMT,
	B.UNIQUE_DATE,
	B.PT_NO,
	B.UNIT_DATE,
	B.UNIT;

DROP TABLE IF EXISTS #ACCTS_WORKED_TBL;
SELECT A.PT_NO,
	A.DEPT,
	A.UNIT_DATE,
	A.UNIT,
	A.ACCTS_WORKED
INTO #ACCTS_WORKED_TBL
FROM (
	SELECT PT_NO,
		DEPT,
		UNIT_DATE,
		UNIT,
		ACCTS_WORKED
	FROM #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL

	UNION ALL

	SELECT PT_NO,
		DEPT,
		UNIT_DATE,
		UNIT,
		ACCTS_WORKED
	FROM #ACCTS_WORKED_IN_SNAPSHOT_TBL
) AS A;

/* ACCOUNTS DOLLARS WORKED

THERE WILL BE ACCOUTNS THAT ARE WORKED BUT NOT IN THE SNAPSHOT FOR VARIOUS REASONS
FOR EXAMPLE THE BALANCE AT SNAPSHOT TIME IS 0 AND IT IS NOT WORKLISTED.

*/
DROP TABLE IF EXISTS #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL;
SELECT B.PT_NO,
	B.DEPT,
	B.UNIT_DATE,
	B.UNIT,
	FOLLOWUP_AMT = SUM(ISNULL(CAST(FOL_AMT AS FLOAT), 0))
INTO #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL
FROM #BASE_POP AS A
RIGHT JOIN SMS.dbo.c_productivity_combined AS B ON A.PT_NO = B.PT_NO
WHERE B.report_run_date = @PRODUCTIVITY_DATE
AND A.PT_NO IS NULL
GROUP BY B.DEPT,
	B.UNIQUE_USER_ID,
	B.FOL_AMT,
	B.UNIQUE_DATE,
	B.PT_NO,
	B.UNIT_DATE,
	B.UNIT;

DROP TABLE IF EXISTS #ACCT_DOLLARS_IN_SNAPSHOT_TBL;
SELECT B.PT_NO,
	B.DEPT,
	B.UNIT_DATE,
	B.UNIT,
	FOLLOWUP_AMT = SUM(ISNULL(CAST(FOL_AMT AS FLOAT), 0))
INTO #ACCT_DOLLARS_IN_SNAPSHOT_TBL
FROM #BASE_POP AS A
LEFT JOIN SMS.dbo.c_productivity_combined AS B ON A.PT_NO = B.PT_NO
WHERE B.report_run_date = @PRODUCTIVITY_DATE
GROUP BY B.DEPT,
	B.UNIQUE_USER_ID,
	B.FOL_AMT,
	B.UNIQUE_DATE,
	B.PT_NO,
	B.unit_date,
	B.UNIT;

DROP TABLE IF EXISTS #ACCTS_DOLLARS_WORKED;
SELECT A.PT_NO,
	A.UNIT_DATE,
	A.UNIT,
	FOLLOWUP_AMT = FOLLOWUP_AMT-- SUM(FOLLOWUP_AMT)
INTO #ACCTS_DOLLARS_WORKED
FROM (
	SELECT PT_NO,
		DEPT,
		UNIT_DATE,
		UNIT,
		FOLLOWUP_AMT
	FROM #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL

	UNION ALL
	
	SELECT PT_NO,
		DEPT,
		UNIT_DATE,
		UNIT,
		FOLLOWUP_AMT
	FROM #ACCT_DOLLARS_IN_SNAPSHOT_TBL
) AS A

-- FIND ACCOUNTS WITH MULTI RECORDS
--SELECT PT_NO
--FROM #ACCTS_DOLLARS_WORKED
--WHERE EXISTS (
--	SELECT 1
--	FROM #BASE_POP AS A
--	WHERE A.PT_NO = PT_NO
--)
--GROUP BY PT_NO
--HAVING COUNT(PT_NO) > 1

/* Pull it all together

Get the account level data along with if the account was worked along with how many
dollars were worked

*/

DROP TABLE IF EXISTS #TEMPA;
SELECT A.PT_NO,
	A.UNIT_NO,
	A.UNIT_DATE,
	A.DEPARTMENT_CLEAN,
	A.WORKABLE_INDICATOR,
	ACCTS_WORKED = (
		SELECT SUM(ACCTS_WORKED)
		FROM #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL AS Z
		WHERE Z.PT_NO = A.PT_NO
			AND ((
				A.UNIT_NO IS NULL
				AND Z.UNIT = 'A'
			)
			OR (
				A.UNIT_NO IS NOT NULL
				AND Z.UNIT != 'A'
				AND A.UNIT_NO = TRY_CONVERT(INT, Z.UNIT)
			))
	),
	DOLLARS_WORKED = (
		SELECT SUM(Z.FOLLOWUP_AMT)
		FROM #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL AS Z
		WHERE Z.PT_NO = A.PT_NO
			AND ((
				A.UNIT_NO IS NULL
				AND Z.UNIT = 'A'
			)
			OR (
				A.UNIT_NO IS NOT NULL
				AND Z.UNIT != 'A'
				AND A.UNIT_NO = TRY_CONVERT(INT, Z.UNIT)
			))
	)
INTO #TEMPA
FROM #BASE_POP AS A;

/*
THE BELOW GETS ACCOUNTS THAT WERE WORKED IN PRODUCTIVITY BUT ARE NOT
SHOWING UP IN THE SNAPSHOT TABLE FOR ONE REASON OR ANTOHER, EXACMPLE
THEY ARE IN BAD DEBT OR THE BALANCE ON THE ACCOUNT IS $0 AND IT IS NOT
WORKLISTED AT THE TIME OF THE SNAPSHOT.
*/
-- GET MISSING DATA, IN PRODUCTIVITY BUT NOT IN SNAPSHOT
-- FIRST CREATE A DEPT TO DEPARTMENT_CLEANED TABLE KEY
-- Create the temporary table
DROP TABLE IF EXISTS #TempDepartments;
CREATE TABLE #TempDepartments (
    DEPT_KEY NVARCHAR(50),
    DEPT NVARCHAR(100)
);

-- Insert data into the temporary table
INSERT INTO #TempDepartments (DEPT_KEY, DEPT) VALUES
('ADMINISTRATION', 'Administration'),
('MEDCO', 'Amplify for the Unit'),
('AUDIT COORDINATOR', 'Audit Coordinator'),
('CASH MANAGEMENT', 'Cash Management'),
('CUSTOMER SERVICE', 'Customer Service'),
('DENIALS AND APPEALS', 'Denials & Appeals'),
('DENIALS AND APPEALS', 'Denials Analyst'),
('SELF PAY AND FINANCIAL ASSIST', 'Financial Assistance'),
('GOVERNMENTAL BILLING', 'Governmental Billing'),
('INSURANCE VERIFICATION', 'Insurance Verification'),
('JOC', 'JOC'),
('NON-GOVERNMENTAL BILLING', 'Non-Governmental Billing'),
('NON-GOVERNMENTAL FOLLOW UP', 'Non-Governmental Follow Up'),
('ANALYST TEAM', 'Pt Acct Management'),
('RESEARCH', 'Research Billing'),
('ANALYST TEAM', 'Revenue Cycle Management'),
('REVENUE INTEGRITY', 'Revenue Integrity'),
('VARIANCE UNIT', 'Revenue, Recovery, Retention Unit'),
('SCA UNIT', 'SCA Unit'),
('TRANSFER BILLING', 'Transfer Billing'),
('UNITIZED FOLLOW UP', 'Unitized Follow Up'),
('VENDOR MANAGEMENT', 'Vendor Management');

-- SECOND CREATE A TBL OF DISTINCT PT_NO, UNIT_NO AND UNIT_DATE
-- ALSO GET DEPARTMENT AND WORKABLE INDICATOR. THIS TEMP TABLE
-- WILL BE JOINED AT THE END TO GET THE ACCT'S WORKED TOTAL
-- AND DOLLARS WORKED TOTAL IN ORDER TO UNION IT TO THE ABOVE
-- QUERY THAT HAS BOTH SNAPSHOT AND PRODUCTIVITY DATA, THIS WILL
-- GIVE US A SINGLE DETAIL TABLE IN WHICH TO PIVOT.
DROP TABLE IF EXISTS #TEMPB;
SELECT A.PT_NO,
	UNIT_NO = CASE 
		WHEN A.UNIT = 'A' 
			THEN NULL 
		ELSE TRY_CONVERT(INT, A.UNIT)
		END,
	A.UNIT_DATE,
	DEPARTMENT_CLEAN = TD.DEPT_KEY,
	WORKABLE_INDICATOR = 'ZZZ NOT IN SNAPSHOT',
	FILE_IND = B.[FILE],
	BALANCE = B.Balance,
	WORKLIST = COALESCE([Worklist Name on Ins1], [Worklist Name on Ins2], [Worklist Name on Ins3], [Worklist Name on Ins4])
INTO #TEMPB
FROM (
	SELECT PT_NO,
		UNIT,
		UNIT_DATE,
		DEPT
	FROM #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL

	UNION 

	SELECT PT_NO,
		UNIT,
		UNIT_DATE,
		DEPT
	FROM #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL
) AS A
LEFT JOIN SMS.DBO.Pt_Accounting_Reporting_for_tableau AS B ON A.PT_NO = B.PT_NO
	AND CASE WHEN A.UNIT != 'A'
		THEN TRY_CONVERT(INT, A.UNIT)
	ELSE ''
	END = ISNULL(B.UNIT_NO, '')
LEFT JOIN #TempDepartments AS TD ON A.DEPT = TD.DEPT;

-- GET ACCTS_WORKED AND DOLLARS_WORKED INTO #TEMPC
DROP TABLE IF EXISTS #TEMPC;
SELECT A.PT_NO,
	A.UNIT_NO,
	A.UNIT_DATE,
	A.DEPARTMENT_CLEAN,
	A.WORKABLE_INDICATOR,
	ACCTS_WORKED = (
		SELECT SUM(ACCTS_WORKED)
		FROM #ACCTS_WORKED_NOT_IN_SNAPSHOT_TBL AS Z
		WHERE Z.PT_NO = A.PT_NO
			AND ((
				A.UNIT_NO IS NULL
				AND Z.UNIT = 'A'
			)
			OR (
				A.UNIT_NO IS NOT NULL
				AND Z.UNIT != 'A'
				AND A.UNIT_NO = TRY_CONVERT(INT, Z.UNIT)
			))
	),
	DOLLARS_WORKED = (
		SELECT SUM(Z.FOLLOWUP_AMT)
		FROM #ACCT_DOLLARS_NOT_IN_SNAPSHOT_TBL AS Z
		WHERE Z.PT_NO = A.PT_NO
			AND ((
				A.UNIT_NO IS NULL
				AND Z.UNIT = 'A'
			)
			OR (
				A.UNIT_NO IS NOT NULL
				AND Z.UNIT != 'A'
				AND A.UNIT_NO = TRY_CONVERT(INT, Z.UNIT)
			))
	),
	A.FILE_IND, 
	A.BALANCE,
	A.WORKLIST
INTO #TEMPC
FROM #TEMPB AS A;

-- BRING IT ALL TOGETHER FOR PRODUCTIVITY
SELECT *
FROM (
	SELECT *,
	FILE_IND = NULL,
	BALANCE = NULL,
	WORKLIST = NULL
	FROM #TEMPA

	UNION

	SELECT *

	FROM #TEMPC
) AS A;