USE [DSH]

SELECT DISTINCT B340.[PA-PT-NO-WOSCD],
       B340.[PA-PT-NO-SCD],
       b340.[PT-NO],
       B340.[admit_date],
       B340.[dsch_date],
       B340.[TYPE],
       INS.[PA-INS-PLAN],
       INS.[PA-INS-PRTY],
       RPTGRP.[MEDICAID-PM-IP-OP-IND],
       B340.[PA-UNIT-NO],
       COALESCE(COSTS.[PA-DTL-REV-CD], COSTS2.[PA-DTL-REV-CD]) AS [PA-DTL-REV-CD],
       COALESCE(COSTS.[Adjusted Rev Code], COSTS2.[Adjusted Rev Code]) AS [Adjusted Rev Code],
       COALESCE(COSTS.[Rev Code from CDM], COSTS2.[Rev Code from CDM]) AS [Rev Code from CDM],
       B340.[PA-DTL-SVC-CD],
	   B340.[UNIT-DATE],
       COSTS.[PA-DTL-DATE],
	   B340.[340B-IND],
       B340.[REPORTING-GROUP],
       sum(B340.[TOT-CHG-QTY]) AS [TOT-QTY],
       (ISNULL(COALESCE(COSTS.[SUM OF TOT PROF FEES], COSTS2.[SUM OF TOT PROF FEES]), 0)) AS [SUM OF TOT PROF FEES],
       (ISNULL(COALESCE(COSTS.[SUM OF TOT CHG], COSTS2.[SUM OF TOT CHG]), 0)) AS [SUM OF TOT CHG],
       (ISNULL(COALESCE(COSTS.[SUM_OF_CHARGESAND_PROF_FEES], COSTS2.[SUM_OF_CHARGESAND_PROF_FEES]), 0)) AS [SUM_OF_CHARGESAND_PROF_FEES]
FROM [DSH].[DBO].[2016_340B_INDICATOR] AS B340
LEFT JOIN [dbo].[2016_DSH_Costs_For_340B] AS COSTS ON B340.[PA-PT-NO-WOSCD] = COSTS.[pa-pt-no-woscd]
       AND B340.[PA-PT-NO-SCD] = COSTS.[PA-PT-NO-SCD]
       AND B340.[PA-UNIT-NO] = COSTS.[PA-UNIT-NO]
       AND B340.[PA-DTL-SVC-CD] = COSTS.[PA-DTL-SVC-CD]
LEFT JOIN [DBO].[2016_DSH_Costs_For_340B] AS COSTS2 ON B340.[PA-PT-NO-WOSCD] = COSTS2.[pa-pt-no-woscd]
       AND B340.[PA-PT-NO-SCD] = COSTS2.[PA-PT-NO-SCD]
       AND B340.[PA-DTL-SVC-CD] = COSTS2.[PA-DTL-SVC-CD]
       AND COSTS2.[PA-UNIT-NO] IS NULL
       AND COSTS2.[UNIT-DATE] IS NULL
LEFT JOIN [dbo].[CUSTOMINSURANCE] AS INS ON B340.[PA-PT-NO-WOSCD] = INS.[pa-pt-no-woscd]
       AND B340.[PA-PT-NO-SCD] = INS.[PA-PT-NO-SCD]
LEFT JOIN [dbo].[DSH_INSURANCE_TABLE_W_REPORT_GROUPS] AS RPTGRP ON B340.[PA-PT-NO-WOSCD] = RPTGRP.[pa-pt-no-woscd]
       AND B340.[PA-PT-NO-SCD] = RPTGRP.[PA-PT-NO-SCD]
WHERE [PA-INS-PRTY] = '1'
       AND [PA-INS-PLAN] IN ('D98', 'D99', 'U01', 'U02', 'U04', 'U05', 'U23', 'U27', 'U31', 'U34', 'U42', 'U57')
--AND B340.[PT-NO] = '10107168642'
GROUP BY B340.[PA-PT-NO-WOSCD],
       B340.[PA-PT-NO-SCD],
       b340.[PT-NO],
       B340.[admit_date],
       B340.[dsch_date],
       B340.[TYPE],
       INS.[PA-INS-PLAN],
       INS.[PA-INS-PRTY],
       RPTGRP.[MEDICAID-PM-IP-OP-IND],
       B340.[PA-UNIT-NO],
       COALESCE(COSTS.[PA-DTL-REV-CD], COSTS2.[PA-DTL-REV-CD]),
       COALESCE(COSTS.[Adjusted Rev Code], COSTS2.[Adjusted Rev Code]),
       COALESCE(COSTS.[Rev Code from CDM], COSTS2.[Rev Code from CDM]),
       B340.[PA-DTL-SVC-CD],
       B340.[UNIT-DATE],
	   COSTS.[PA-DTL-DATE],
       B340.[340B-IND],
       B340.[REPORTING-GROUP],
       (ISNULL(COALESCE(COSTS.[SUM OF TOT PROF FEES], COSTS2.[SUM OF TOT PROF FEES]), 0)),
       (ISNULL(COALESCE(COSTS.[SUM OF TOT CHG], COSTS2.[SUM OF TOT CHG]), 0)),
       (ISNULL(COALESCE(COSTS.[SUM_OF_CHARGESAND_PROF_FEES], COSTS2.[SUM_OF_CHARGESAND_PROF_FEES]), 0))
       ;


       ------------------BELOW QUERIES CREATED TO CHECK THAT MAIN QUERY DATA WAS YIELDING CORRECT INFORMATION.  BELOW QUERIES HELPED US ADJUST ABOVE CODING SO CHARGES AND QUANTITIES WERE CORRECT IN MAIN QUERY ABOVE.  NEXT YEAR SELECT AN ENCOUNTER IN ABOVE MAIN QUERY
       ---AND REPLACE THAT ENCOUNTER WITH THE TEST ENCOUNTER FEATURED BELOW.  UNCOMMENT THE BELOW QUERIES AND RUN.  COMPARE RESULTS FOR TEST ENCOUNTER(S) TO MAKE SURE ALL INFORMATION (I.E., CHARGES, QUANTITIES, ETC ARE CORRECT FOR MAIN QUERY OUTPUT).  
       ---COMMENT OUT BELOW QUERIES AGAIN FOR FUTURE REFERENCE AFTER USED FOR TESTING ANNUAL DATA-----

--SELECT A.[PA-PT-NO-WOSCD],
--     A.[PA-PT-NO-SCD],
--     A.[PT-NO],
--     A.[PA-UNIT-NO],
--     A.[admit_date],
--     A.[dsch_date],
--     A.[TYPE],
--     C.[PA-INS-PLAN],
--     A.[PA-DTL-SVC-CD],
--     A.[340B-IND],
--     A.[REPORTING-GROUP],
--     A.[PA-DTL-CDM-DESCRIPTION],
--     sum(A.[TOT-CHG-QTY]) AS [TOT-QTY],
--     sum(A.[Total Charges including Prof Fees]) AS [TOT-CHGS-INCLUDING-PROF-FEES]
--FROM [DBO].[2016_340B_INDICATOR] AS A
--LEFT OUTER JOIN [dbo].[CUSTOMINSURANCE] AS C ON A.[PA-PT-NO-WOSCD] = C.[pa-pt-no-woscd]
--     AND A.[PA-PT-NO-SCD] = C.[PA-PT-NO-SCD]
--     WHERE A.[PT-NO] = '10107168642'
--     AND C.[PA-INS-PRTY] = '1'
--     AND C.[PA-INS-PLAN] IN ('D98', 'D99', 'U01', 'U02', 'U04', 'U05', 'U23', 'U27', 'U31', 'U34', 'U42', 'U57')
--GROUP BY A.[PA-PT-NO-WOSCD],
--     A.[PA-PT-NO-SCD],
--     A.[PT-NO],
--     A.[PA-UNIT-NO],
--     A.[admit_date],
--     A.[dsch_date],
--     A.[TYPE],
--     C.[PA-INS-PLAN],
--     A.[PA-DTL-SVC-CD],
--     A.[340B-IND],
--     A.[REPORTING-GROUP],
--     A.[PA-DTL-CDM-DESCRIPTION];

--SELECT [pa-pt-no-woscd],
--     [PA-PT-NO-SCD],
--     [PT-NO],
--     [PA-UNIT-NO],
--     [TYPE],
--     [PA-DTL-SVC-CD],
--     [PA-DTL-REV-CD],
--     [ADJUSTED REV CODE],
--     [Rev Code from CDM],
--     *
--FROM [DBO].[2016_DSH_Costs]

--WHERE left([pa-dtl-svc-cd], 3) = '415'
--and [PT-NO] = '10107168642'
-- ;

--SELECT [PA-PT-NO-WOSCD],
--     [PA-PT-NO-SCD],
--     *
--FROM [dbo].[CUSTOMINSURANCE]
--WHERE [PA-PT-NO-WOSCD] = '1010716864'
--     AND [PA-PT-NO-SCD] = '2'
--     AND [PA-INS-PRTY] = 1;
