/*
***********************************************************************
File: c_INST_JOIN_ALL_v.sql

Input Parameters:
	None

Tables/Views:
    [SMS].[dbo].[c_INST_v]
    [SMS].[dbo].[c_INST_info_code_v]
	[SMS].[dbo].[c_INST_line_v]
	[SMS].[dbo].[c_INST_line_svd_v]
	[SMS].[dbo].[c_INST_line_svd_cas_v]
	[SMS].[dbo].[c_INST_other_sub_v]
	[SMS].[dbo].[c_INST_other_sub_cas_v]

Creates Table/View:
	dbo.c_INST_JOIN_ALL_v
	

Functions:
	None

Author: Fang Wu

Department: Patient Financial Services

Purpose/Description
	Create a View to join 4 REMIT tables from EMSEE database in SMS database 

Revision History:
Date		Version		Description
----		----		----
2023-09-06	v1			Initial Creation
***********************************************************************
*/

IF EXISTS (
    SELECT
        *
    FROM
        sys.views
        JOIN sys.schemas ON sys.views.schema_id = sys.schemas.schema_id
    WHERE
        sys.schemas.name = N'dbo'
        AND sys.views.name = N'c_INST_JOIN_All_v'
) DROP VIEW dbo.c_INST_JOIN_ALL_v
GO

-- Create the view in the specified schema

CREATE VIEW dbo.c_INST_JOIN_ALL_v AS

Select a.[Patient_Account_Number]
,a.[Pt_NO]
,a.[Ins_CD]
,a.[Unit_NO]
,a.[Seq_No]
,a.[INST]
,a.[Export_Date_Time]
,a.[File_Name]
,a.[Interchange_Sender_ID]
,a.[Interchange_Receiver_ID]
,a.[Interchange_Control_Number]
,a.[File_Creation_Date]
,a.[EDI_Version]
,a.[EDI_Format]
,a.[Transaction_Set_Control_Number]
,a.[EDI_Purpose_Code]
,a.[Originator_Application_Transaction_ID]
,a.[Submitter_Name]
,a.[Submitter_ID]
,a.[Submitter_Contact]
,a.[Submitter_Contact_Method]
,a.[Receiver_Name]
,a.[Receiver_ID]
,a.[Billing_Provider_Specialty_Code]
,a.[Billing_Provider]
,a.[Billing_Provider_ID]
,a.[Billing_NPI]
,a.[Billing_Provider_Address]
,a.[Billing_Address_1]
,a.[Billing_Address_2]
,a.[Billing_City]
,a.[Billing_State]
,a.[Billing_ZIP]
,a.[Billing_Provider_Tax_ID]
,a.[Pay_To_Address]
,a.[Pay_To_Address1]
,a.[Pay_To_Address2]
,a.[Pay_To_City]
,a.[Pay_To_State]
,a.[Pay_To_ZIP]
,a.[Pay_To_Plan_Name]
,a.[Pay_To_Plan_ID]
,a.[Pay_To_Plan_Address]
,a.[Payer_Sequence_Number]
,a.[Individual_Relationship_Code]
,a.[Subscriber_Group_or_Policy_Number]
,a.[Billed_Insured_Group]
,a.[Claim_Filing_Indicator_Code]
,a.[Billed_Subscriber_Name]
,a.[Billed_Subscriber_Entity_Type]
,a.[Billed_Subscriber_Last_Name]
,a.[Billed_Subscriber_First_Name]
,a.[Billed_Subscriber_Middle_Name]
,a.[Billed_Subscriber_ID]
,a.[Subscriber_Address1]
,a.[Subscriber_Address2]
,a.[Subscriber_City]
,a.[Subscriber_State]
,a.[Subscriber_Zip]
,a.[Subscriber_Gender]
,a.[Subscriber_DOB]
,a.[Subscriber_Secondary_ID]
,a.[Subscriber_Property_Casualty_Claim_Number]
,a.[Payer_Name]
,a.[Payer_ID_Code_Qualifier]
,a.[Payer_ID]
,a.[Payer_Address_1]
,a.[Payer_Address_2]
,a.[Payer_City]
,a.[Payer_State]
,a.[Payer_Zip]
,a.[Billing_Provider_Secondary_ID]
,a.[Payer_Secondary_ID]
,a.[Provider_Commercial_Number]
,a.[Patient_Name]
,a.[Patient_Address1]
,a.[Patient_Address2]
,a.[Patient_City]
,a.[Patient_State]
,a.[Patient_Zip]
,a.[Patient_DOB]
,a.[Patient_Gender]
,a.[Patient_Property_Casualty_Claim_Number]
,a.[Charge_Amount]
,a.[Facility_Type_Code]
,a.[Facility_Code]
,a.[Frequency_Code]
,a.[Delay_Reason_Code]
,a.[Discharge_Hour]
,a.[Statement_Dates]
,a.[Statement_From_Date]
,a.[Statement_Through_Date]
,a.[Admission_Date_Time]
,a.[Repricer_Received_Date]
,a.[Inst_Claim_Code]
,a.[Admission_Type_Code]
,a.[Admission_Source_Code]
,a.[Patient_Status_Code]
,a.[Attachment_Report_Type_Code]
,a.[Attachment_Transmission_Code]
,a.[Attachment_Control_Number]
,a.[Contract_Type_Code]
,a.[Contract_Amount]
,a.[Contract_Code]
,a.[Patient_Amount_Due]
,a.[Claim_Approved_Amount]
,a.[SAE_Code]
,a.[Prior_Authorization]
,a.[Clearinghouse_Trace_Number]
,a.[Repriced_Claim_Number]
,a.[Repriced(Adj_)_Claim_Number]
,a.[Investigational_Device_Exemption_ID]
,a.[Original_Reference_Number]
,a.[Auto_Accident_State]
,a.[Medical_Record_Number]
,a.[Demonstration_Project_ID]
,a.[Referral_Number]
,a.[Payers_DCN]
,a.[Claim_Note]
,a.[Claim_Billing_Note]
,a.[Repriced_Methodology]
,a.[Repriced_Allowed_Amount]
,a.[Repriced_Savings_Amount]
,a.[Repricing_Organization_ID]
,a.[Reject_Reason_Code]
,a.[Reject_Reason]
,a.[Attending_Phys_ID]
,a.[Attending_Phys]
,a.[Attending_Phys_Last_Name]
,a.[Attending_Phys_First_Name]
,a.[Attending_Phys_Middle_Name]
,a.[Attending_Phys_Specialty]
,a.[Attending_Phys_Sec_ID]
,a.[Operating_Phys_ID]
,a.[Operating_Phys]
,a.[Other_Operating_Phys_ID]
,a.[Other_Operating_Phys]
,a.[Rendering_Provider_ID]
,a.[Rendering_Provider]
,a.[Service_Facility]
,a.[Service_Facility_Name]
,a.[Service_Facility_ID]
,a.[Service_Facility_Address]
,a.[Service_Facility_Address_1]
,a.[Service_Facility_Address_2]
,a.[Service_Facility_City]
,a.[Service_Facility_State]
,a.[Service_Facility_ZIP]
,a.[Service_Facility_Secondary_ID]
,a.[Service_Facility_Location_Number]
,a.[Referring_Provider_ID]
,a.[Referring_Provider]
,a.[id_type]
,a.[number]
,a.[parent_name]
,a.[parent_name_extended]
,b.[INST_info_code]
--,b.[INST]
,b.[info_Code_description]
,b.[info_Code_description_short]
,b.[info_Code_qualifier]
,b.[info_Code]
,b.[info_Code_Date]
,b.[info_Code_Date_Through]
,b.[info_Code_Amount]
,b.[info_Code_Quantity]
,b.[info_Code_VersionID]
,b.[info_Code_Industry_Code]
,b.[info_Code_Response_Code]
,c.[INST_other_sub]
--,c.[INST]
,c.[Second_Subscriber_Sequence_Number]
,c.[Second_Subscriber_Relationship_Code]
,c.[Second_Sub_Insured_Group_Number]
,c.[Second_Sub_Insured_Group]
,c.[Second_Sub_Coordination_of_Benefits_Code]
,c.[Second_Sub_Claim_Filing_Indicator]
,c.[Prior_Payers_Claim_Level_Deductible_Amounts]
,c.[Prior_Payers_Claim_Level_Coinsurance_Amounts]
,c.[Prior_Payers_Claim_Level_Copay_Amounts]
,c.[Prior_Payers_Claim_Level_Other_Adjustment_Amts]
,c.[Prior_Payers_Claim_Level_All_Adjustments_in_Total]
,c.[Second_Sub_COB_Payer_Paid_Amt]
,c.[Prior_Payers_Claim_Level_Amount_Paid]
,c.[Second_Sub_Patient_Liability]
,c.[Prior_Payers_Claim_Level_Non_Covered_Amounts]
,c.[Second_Sub_COB_Non_Covered_Amt]
,c.[Second_Sub_MIA]
,c.[Second_Sub_MOA]
,c.[Second_Subscriber_ID]
,c.[Second_Subscriber_Name]
,c.[Second_Subscriber_Last_Name]
,c.[Second_Subscriber_First_Name]
,c.[Second_Subscriber_Middle_Name]
,c.[Second_Sub_Payer_ID]
,c.[Second_Sub_Payer]
,c.[Second_Sub_Date_Claim_Paid]
,c.[Second_Sub_Original_Reference_Number]
,c.[Second_Sub_Other_Payers_Adjusted_Claim_Control_Number]
,d.[Line_Control_Number]
--,d.[Pt_NO]
--,d.[Ins_CD]
--,d.[Unit_NO]
--,d.[Seq_No]
,d.[Line_No]
,d.[INST_line]
--,d.[INST]
,d.[Line_Serial]
,d.[Line_Revenue_Code]
,d.[Line_Product_or_Service_ID_Qualifier]
,d.[Line_Procedure_Code]
,d.[Line_Procedure_Modifiers]
,d.[Line_Procedure_Modifier_1]
,d.[Line_Procedure_Modifier_2]
,d.[Line_Procedure_Modifier_3]
,d.[Line_Procedure_Modifier_4]
,d.[Line_Procedure_Description]
,d.[Line_Amount_Total]
,d.[Line_Units_Code]
,d.[Line_Units]
,d.[Line_Attachment_Control_Number]
,d.[Line_Service_Date]
,d.[FS_Allowed_Amount]
,d.[UC_Allowed_Amount]
,d.[Line_Note]
,d.[Line_Pricing_Methodology]
,d.[Line_Repriced_Allowed_Amount]
,d.[Line_Repriced_Savings_Amount]
,d.[Line_Repricing_Organization_ID]
,d.[Line_Repriced_Approved_HCPCS_Code]
,d.[Line_Repriced_Measurment_Code]
,d.[Line_Repriced_Quantity]
,d.[Line_Reject_Reason_Code]
,d.[Line_Reject_Reason]
,d.[NDC_Number]
,d.[Drug_Quantity]
,d.[Composite_Unit_Of_Measure]
,d.[Prescription_Number]
,d.[Prior_Payers_Service_Level_Amount_Paid]
,e.[INST_other_sub_cas]
--,e.[INST_other_sub]
--,e.[INST]
,e.[claim_Adjustment_Group_Code]
,e.[claim_Adjustment_Reason_Code]
,e.[claim_Adjustment_Reason_Description]
,e.[claim_Adjustment_Amount]
,e.[claim_Adjustment_Quantity]
,f.[INST_line_svd]
--,f.[INST_line]
--,f.[INST]
,f.[Line_Adjudication_Other_Payer_ID_1]
,f.[Line_Adjudication_Paid_Amount_1]
,f.[Line_Adjudication_Procedure_Code_1]
,f.[Line_Adjudication_Revenue_Code_1]
,f.[Line_Adjudication_Quantity_1]
,f.[Line_Adjudication_Date]
,g.[INST_line_svd_cas]
--,g.[INST_line_svd]
--,g.[INST_line]
--,g.[INST]
,g.[line_Adjustment_Group_Code]
,g.[line_Adjustment_Reason_Code]
,g.[line_Adjustment_Reason_Description]
,g.[line_Adjustment_Amount]
,g.[line_Adjustment_Quantity]




from [dbo].[c_INST_v] a left join [dbo].[c_INST_info_code_v] b
on a.[inst]=b.[inst]
left join [dbo].[c_INST_other_sub_v] c
on a.[inst]=c.[inst]
left join [dbo].[c_INST_line_v] d
on a .[inst]=d.[inst]
left join [dbo].[c_INST_other_sub_cas_v] e
on c.[INST_other_sub]=e.[INST_other_sub_cas]
left join [dbo].[c_INST_line_svd_v] f
on d.[INST_line]=f.[INST_line]
left join [dbo].[c_INST_line_svd_cas_v] g
on f.[INST_line_svd]=g.[INST_line_svd]

Go