SELECT DISTINCT [track_id] = '14917',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) != 0
)
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	(
		PD.[PA-BAL-ACCT-BAL] = 0
		OR PD.[PA-BAL-TOT-INS-BAL] = 0
		OR PD.[PA-PAY-SCALE] IN ('G','6')
	)
	AND (
		PD.[PA-PT-REPRESENTATIVE] IS NULL
		OR PD.[PA-PT-REPRESENTATIVE] IN ('590','591','593','470')
	)
)

UNION ALL

SELECT DISTINCT [track_id] = '14917',
	[spol_group] = 'Group_2',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE (
	PD.[PA-FINAL-BILL-DATE] IS NOT NULL
	OR PD.[PA-OP-FIRST-INS-BL-DATE] IS NOT NULL
	OR UA.[PA-UNIT-OP-FIRST-INS-BL-DATE] IS NOT NULL
)
AND I1.[PA-INS-CO-CD] = 'H'
AND I1.[PA-INS-PLAN-NO] = '3'
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) != 0
)
AND EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '79802'
	AND DI.[PA-DTL-POST-DATE] = DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
)