SELECT DISTINCT [track_id] = '12871',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR),
	[unit_no] = UA.[PA-UNIT-NO],
	[unit_date] = CAST(UA.[PA-UNIT-DATE] AS DATE)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE UA.[PA-UNIT-DATE] >= '2013-01-01'
AND UA.[PA-UNIT-FC] IN ('V','Y','R','T')
--AND I1.[PA-LAST-INS-PAY-DATE] BETWEEN DATEADD(DAY, -31, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.AccountComments AS AC
	WHERE AC.[PA-PT-NO-WOSCD] = PD.[PA-PT-NO-WOSCD]
	AND AC.[PA-PT-NO-SCD-1] = PD.[PA-PT-NO-SCD-1]
	AND (
		AC.[PA-SMART-SVC-CD-WOSCD] = '50399'
		OR (
			AC.[PA-SMART-COMMENT] LIKE 'EBC  REASON CODE=%'
			AND (
				TRY_CAST(SUBSTRING(AC.[PA-SMART-COMMENT], CHARINDEX('=', AC.[PA-SMART-COMMENT]) + 1, 3) AS INT) BETWEEN 40 AND 409
				OR TRY_CAST(SUBSTRING(AC.[PA-SMART-COMMENT], CHARINDEX('=', AC.[PA-SMART-COMMENT]) + 1, 3) AS INT) BETWEEN 96 AND 969
			)
		)
	)
)
AND (
	(
		ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
		AND ISNULL(UA.[PA-UNIT-INS1-BAL], 0) = 0
	)
	OR (
		(
			ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
			OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) != 0
		)
		AND (
			ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) < 300
			OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) < 300 
		)
		AND UA.[PA-UNIT-PT-BAL] < 0
	)
	AND (
		(
			I1.[PA-INS-CO-CD] = 'C'
			AND I1.[PA-INS-PLAN-NO] IN ('50','90')
			AND I2.[PA-INS-CO-CD] = 'G'
			AND I2.[PA-INS-PLAN-NO] = '31'
		)
		OR (
			I1.[PA-INS-CO-CD] = 'C'
			AND I1.[PA-INS-PLAN-NO] IN ('49','99')
			AND I2.[PA-INS-CO-CD] IN ('P','G')
			AND I2.[PA-INS-PLAN-NO] = '12'

		)

	)
	AND (
		PD.[PA-PT-REPRESENTATIVE] IS NULL
		OR PD.[PA-PT-REPRESENTATIVE] IN ('580','581','582','583','590','591','592','593')
	)
)

UNION ALL

SELECT DISTINCT [track_id] = '12871',
	[spol_group] = 'Group_2',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR),
	[unit_no] = UA.[PA-UNIT-NO],
	[unit_date] = CAST(UA.[PA-UNIT-DATE] AS DATE)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE (
	PD.[PA-FINAL-BILL-DATE] IS NOT NULL
	OR PD.[PA-OP-FIRST-INS-BL-DATE] IS NOT NULL
	OR UA.[PA-UNIT-OP-FIRST-INS-BL-DATE] IS NOT NULL
)
AND I2.[PA-INS-CO-CD] = 'H'
AND I2.[PA-INS-PLAN-NO] IN ('1','99')
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) != 0
)