SELECT  DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
WHERE PD.[PA-ACCT-TYPE] = '0'
AND PD.[PA-UNIT-STS] != 'U'
AND PD.[PA-LAST-FC] IN ('V','Y','R','T')
AND I1.[PA-LAST-INS-PAY-DATE] IS NOT NULL
AND PD.[PA-ADM-DATE] >= '2013-01-01'
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE DI.[PA-PT-NO-WOSCD] = PD.[PA-PT-NO-WOSCD]
	AND DI.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.AccountComments AS AC
	WHERE AC.[PA-PT-NO-WOSCD] = PD.[PA-PT-NO-WOSCD]
	AND AC.[PA-PT-NO-SCD-1] = PD.[PA-PT-NO-SCD-1]
	AND (
		AC.[PA-SMART-SVC-CD-WOSCD] = '50399'
		OR (
			AC.[PA-SMART-COMMENT] LIKE 'EBC  REASON CODE=%'
			AND (
				TRY_CAST(SUBSTRING(AC.[PA-SMART-COMMENT], CHARINDEX('=', AC.[PA-SMART-COMMENT]) + 1, 3) AS INT) BETWEEN 40 AND 409
				OR TRY_CAST(SUBSTRING(AC.[PA-SMART-COMMENT], CHARINDEX('=', AC.[PA-SMART-COMMENT]) + 1, 3) AS INT) BETWEEN 96 AND 969
			)
		)
	)
)
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	OR (
		ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
		AND ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) < 300
		AND PD.[PA-BAL-PT-BAL] < 0.1
		AND (
			(
				I1.[PA-INS-CO-CD] = 'C'
				AND I1.[PA-INS-PLAN-NO] IN ('50','90')
				AND I2.[PA-INS-CO-CD] = 'G'
				AND I2.[PA-INS-PLAN-NO] = '31'
				AND ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
			)
			OR (
				I1.[PA-INS-CO-CD] = 'C'
				AND I1.[PA-INS-PLAN-NO] IN ('49','99')
				AND I2.[PA-INS-CO-CD] IN ('P','G')
				AND I2.[PA-INS-PLAN-NO] = '12'
				AND ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
			)
			OR (
				PD.[PA-ACCT-TYPE] = '0'
				AND I1.[PA-INS-CO-CD] = 'M'
				AND I2.[PA-INS-CO-CD] = 'B'
				AND I2.[PA-INS-PLAN-NO] IN ('14','99')
			)
		)
	)
)
AND (
	PD.[PA-PT-REPRESENTATIVE] IS NULL
	OR PD.[PA-PT-REPRESENTATIVE] IN ('580','581','582','583','590','591','592','593')
)

UNION ALL

SELECT  DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_2',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
	AND I1.[PA-INS-PRTY] = '2'
	AND I1.[PA-INS-CO-CD] = 'H'
	AND I1.[PA-INS-PLAN-NO] IN ('01','99')
	AND (
		ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
		OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) != 0
	)
	AND (
		PD.[PA-FINAL-BILL-DATE] IS NOT NULL
		OR PD.[PA-OP-FIRST-INS-BL-DATE] IS NOT NULL
		OR UA.[PA-UNIT-OP-FIRST-INS-BL-DATE] IS NOT NULL
	)
	
UNION ALL

SELECT  DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_3',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND PD.[PA-ACCT-TYPE] = '0'
AND I1.[PA-INS-CO-CD] = 'M'
AND I1.[PA-LAST-INS-BL-DATE] = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE)
AND I1.[PA-INS-PRTY] = '1'
AND I2.[PA-INS-PRTY] = '2'
AND I2.[PA-INS-CO-CD] = 'B'
AND I2.[PA-INS-PLAN-NO] = '14'
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)

UNION ALL

SELECT  DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_4',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE I1.[PA-INS-CO-CD] = 'A'
AND I1.[PA-INS-PLAN-NO] = '4'
AND I1.[PA-INS-PRTY] = '2'
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND (
		(
			DI.[PA-DTL-SVC-CD-WOSCD] IN ('82004', '3816603','3816604')
			AND DI.[PA-DTL-POST-DATE] = DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
		)
		OR (
			DI.[PA-DTL-SVC-CD-WOSCD] IN ('50315','3816603','3816604')
			AND DI.[PA-DTL-POST-DATE] = DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
			AND DI.[PA-DTL-INS-CD] = '242'
		)
	)
)

UNION ALL

SELECT  DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_5',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND I1.[PA-INS-CO-CD] = 'C'
AND I1.[PA-INS-PLAN-NO] = '49'
AND I2.[PA-INS-CO-CD] = 'P'
AND I2.[PA-INS-PLAN-NO] = '12'
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND I1.[PA-INS-SUBSCR-INS-GROUP-ID] = I2.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	I1.[PA-LAST-INS-PAY-DATE] IS NOT NULL
	OR EXISTS (
		SELECT 1
		FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
		WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
		AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
		AND DI.[PA-DTL-SVC-CD-WOSCD] IN ('3816604','3816603')
		AND DI.[PA-DTL-INS-CD] = '242'
		AND DI.[PA-DTL-POST-DATE] BETWEEN DATEADD(DAY, -31, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
	)
)

UNION ALL

SELECT DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_6',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '80107'
	AND DI.[PA-DTL-INS-CD] = '242'
	AND DI.[PA-DTL-POST-DATE] BETWEEN DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
)

UNION ALL

SELECT DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_7',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND I1.[PA-INS-CO-CD] = 'M'
AND I1.[PA-INS-PLAN-NO] = '55'
AND I2.[PA-INS-CO-CD] = 'N'
AND I2.[PA-INS-PLAN-NO] = '45'
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] IN ('3816604','3816603')
	AND DI.[PA-DTL-INS-CD] = '242'
	AND DI.[PA-DTL-POST-DATE] BETWEEN DATEADD(DAY, -31, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
)

UNION ALL

SELECT DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_8',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND I1.[PA-LAST-INS-PAY-DATE] IS NOT NULL
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) = 0
)
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND I1.[PA-INS-CO-CD] = 'C'
AND I1.[PA-INS-PLAN-NO] = '49'
AND I2.[PA-INS-CO-CD] = 'P'
AND I2.[PA-INS-PLAN-NO] = '12'
AND PD.[PA-HOSP-SVC] IN (
	'ABC','ABD','APV','ARI','ARY','CAR','COU','CPT','CRD','DIB','EMT','GNO','LAB','LGD','LSA','LSA','MCT','MOT',
	'MRI','NBS','NPT','ORC','PES','PFT','PST','PTP','RAN','RDO','RTP','SAT','SDO','SGY','TEG','TUR','VAS','XRY'
)
AND I2.[PA-INS-SUBSCR-INS-GROUP-ID] = I3.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] IN ('50399')
)

UNION ALL

SELECT DISTINCT [track_id] = '12870',
	[spol_group] = 'Group_9',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND I1.[PA-LAST-INS-PAY-DATE] IS NOT NULL
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) = 0
)
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	)
AND I1.[PA-INS-CO-CD] = 'C'
AND I1.[PA-INS-PLAN-NO] = '50'
AND I2.[PA-INS-CO-CD] = 'G'
AND I2.[PA-INS-PLAN-NO] = '31'
AND PD.[PA-HOSP-SVC] IN (
	'ELC','PAT'
)
AND I2.[PA-INS-SUBSCR-INS-GROUP-ID] = I3.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] IN ('50399')
)