SELECT DISTINCT [track_id] = '12756',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND PD.[PA-NO-OF-INS-CLAIMED] = 2
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) = 0
)
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
)
AND I2.[PA-INS-CO-CD] IN ('C','G','J','M','N','O','P','Y')
AND I2.[PA-LAST-INS-PAY-DATE] IS NULL
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)