/*
UNIT STATUS DOES NOT EQUAL 'U'
BILL DATE IS NOT NULL
INS3 PLAN ID IN H01, H99
INS3 TOTAL BALANCE IS NOT NULL AND NOT 0
*/

SELECT  DISTINCT [track_id] = '13152',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS II ON PD.[PA-PT-NO-WOSCD] = II.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = II.[PA-PT-NO-SCD-1]
	AND II.[PA-INS-CO-CD] = 'H'
	AND II.[PA-INS-PLAN-NO] IN ('1','99')
	AND II.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	PD.[PA-FINAL-BILL-DATE] IS NOT NULL
	OR PD.[PA-OP-FIRST-INS-BL-DATE] IS NOT NULL
	OR UA.[PA-UNIT-OP-FIRST-INS-BL-DATE] IS NOT NULL
	)
AND (
	(
		II.[PA-BAL-INS-PROR-NET-AMT] IS NOT NULL
		AND II.[PA-BAL-INS-PROR-NET-AMT] != 0
	)
	OR (
		UA.[PA-UNIT-INS1-BAL] IS NOT NULL
		AND UA.[PA-UNIT-INS1-BAL] != 0
	)
)

UNION ALL

/*
GROUP 2
UNIT STATUS NOT EQUAL TO 'U'
INS1 PLAN ID EQUALS C49
INS3 PLAN ID EQUALS P12
INS3 TOT BAL GREATER THAN 0 AND NOT NULL
INS2 SUBSCRIBER INS GROUP ID EQUALS INS3 POLICY NO
HAS NO SERVICE CODE 50399 
LAST INS PAY DATE IS NOT NULL
OR
HAS SERVICE CODE 3816604 OR 3816603
INS CODE EQUALS 243
POST DATE BETWEEN 22 DAYS AGO AND 1 DAY AGO
*/

SELECT DISTINCT [track_id] = '13152',
	[spol_group] = 'Group_2',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS II ON PD.[PA-PT-NO-WOSCD] = II.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = II.[PA-PT-NO-SCD-1]
	AND II.[PA-INS-CO-CD] = 'C'
	AND II.[PA-INS-PLAN-NO] = '49'
	AND II.[PA-INS-PRTY] = '2'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS II2 ON PD.[PA-PT-NO-WOSCD] = II2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = II2.[PA-PT-NO-SCD-1]
	AND II2.[PA-INS-CO-CD] = 'P'
	AND II2.[PA-INS-PLAN-NO] = '12'
	AND II2.[PA-INS-PRTY] = '3'
	AND ISNULL(II2.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
	AND ISNULL(UA.[PA-UNIT-INS2-BAL], 0) > 0
	AND ISNULL(UA.[PA-UNIT-INS3-BAL], 0) > 0
WHERE PD.[PA-UNIT-STS] != 'U'
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	II.[PA-LAST-INS-PAY-DATE] IS NOT NULL
	OR EXISTS (
		SELECT 1
		FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
		WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
		AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
		AND Z.[PA-DTL-SVC-CD-WOSCD] IN ('3816604', '3816603')
		AND Z.[PA-DTL-INS-CD] = '243'
		AND CAST(Z.[PA-DTL-POST-DATE] AS DATE) BETWEEN DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
	)
)

UNION ALL

/*
GROUP 3
UNIT STATUS NOT EQUAL TO 'U'
INS3 PLAN ID EQUALS C49
INS3 PRIORITY EQUALS 3
INS3 TOTAL BALANCE GREATER THAN 0
OR
INS3 UNITIZED ACCOUNT BALANCE GREATER THAN 0
*/

SELECT DISTINCT [track_id] = '13152',
	[spol_group] = 'Group_3',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS II ON PD.[PA-PT-NO-WOSCD] = II.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = II.[PA-PT-NO-SCD-1]
	AND II.[PA-INS-CO-CD] = 'C'
	AND II.[PA-INS-PLAN-NO] = '49'
	AND II.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI ON PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '80107'
	AND DI.[PA-DTL-INS-CD] = '243'
	AND CAST(DI.[PA-DTL-POST-DATE] AS DATE) BETWEEN DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
WHERE PD.[PA-UNIT-STS] != 'U'
AND II.[PA-INS-PRTY] = '3'
AND (
	ISNULL(II.[PA-BAL-INS-PROR-NET-AMT] , 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS3-BAL], 0) > 0
)

/*
GROUP 4
*/

UNION ALL

SELECT DISTINCT [track_id] = '13152',
	[spol_group] = 'Group_4',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS II ON PD.[PA-PT-NO-WOSCD] = II.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = II.[PA-PT-NO-SCD-1]
	AND ISNULL(II.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	AND II.[PA-INS-PRTY] = '1'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
	AND I2.[PA-INS-PRTY] = '2'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND ISNULL(I3.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	AND I3.[PA-INS-PRTY] = '3'
	AND I3.[PA-INS-CO-CD] = 'C'
	AND I3.[PA-INS-PLAN-NO] = '49'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I4 ON PD.[PA-PT-NO-WOSCD] = I4.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I4.[PA-PT-NO-SCD-1]
	AND I4.[PA-INS-PRTY] = '4'
	AND I4.[PA-INS-CO-CD] = 'P'
	AND I4.[PA-INS-PLAN-NO] = '12'
WHERE PD.[PA-UNIT-STS] != 'U'
AND PD.[PA-HOSP-SVC] IN (
	'ABC','ABD','APV','ARI','ARY','CAR','COU','CPT','CRD','DIB','EMT','BNO','LAB','LGD','LSA','MCT','MOT','MRI','NBS','NPT','ORC',
	'PES','PFT','PST','PTP','RAN','RDO','RTP','SAT','SDO','SGY','TEG','TUR','VAS','XRY'
	)
AND I3.[PA-INS-SUBSCR-INS-GROUP-ID] = I4.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	I2.[PA-LAST-INS-PAY-DATE] IS NOT NULL
	OR I3.[PA-LAST-INS-PAY-DATE] IS NOT NULL
)

UNION ALL

/*
GROUP 5
*/

SELECT  DISTINCT [track_id] = '13152',
	[spol_group] = 'Group_5',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I2.[PA-INS-PRTY] = '2'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I3.[PA-INS-PRTY] = '3'
INNER JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I4 ON PD.[PA-PT-NO-WOSCD] = I4.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I4.[PA-PT-NO-SCD-1]
	AND I4.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
AND ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) = 0
AND ISNULL(I3.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
AND I3.[PA-INS-CO-CD] = 'C'
AND I3.[PA-INS-PLAN-NO] = '50'
AND I4.[PA-INS-CO-CD] = 'G'
AND I4.[PA-INS-PLAN-NO] = '31'
AND PD.[PA-HOSP-SVC] IN ('ELC','PAT')
AND I3.[PA-INS-SUBSCR-INS-GROUP-ID] = I4.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	I1.[PA-LAST-INS-PAY-DATE] IS NOT NULL
	OR I2.[PA-LAST-INS-PAY-DATE] IS NOT NULL
)