SELECT DISTINCT [track_id] = '12758',
	[spol_group] = 'Group_1',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	PD.[PA-FINAL-BILL-DATE] IS NOT NULL
	OR PD.[PA-OP-FIRST-INS-BL-DATE] IS NOT NULL
	OR UA.[PA-UNIT-OP-FIRST-INS-BL-DATE] IS NOT NULL
)
AND I1.[PA-INS-CO-CD] = 'H'
AND I1.[PA-INS-PLAN-NO] IN ('1','99')
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS4-BAL], 0) != 0
)

UNION ALL

SELECT DISTINCT [track_id] = '12758',
	[spol_group] = 'Group_2',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS4-BAL], 0) != 0
)
AND (
	(
		PD.[PA-BAL-ACCT-BAL] = 0
		OR PD.[PA-BAL-TOT-INS-BAL] = 0
		OR PD.[PA-PAY-SCALE] IN ('G','6')
	)
	AND (
		PD.[PA-PT-REPRESENTATIVE] IS NULL
		OR PD.[PA-PT-REPRESENTATIVE] IN ('590','591','593')
	)
)

UNION ALL

SELECT DISTINCT [track_id] = '12758',
	[spol_group] = 'Group_3',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I4 ON PD.[PA-PT-NO-WOSCD] = I4.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I4.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	ISNULL(I1.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS1-BAL], 0) != 0
)
AND (
	ISNULL(I2.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS2-BAL], 0) != 0
)
AND (
	ISNULL(I3.[PA-BAL-INS-PROR-NET-AMT], 0) != 0
	OR ISNULL(UA.[PA-UNIT-INS3-BAL], 0) != 0
)
AND (
	ISNULL(I4.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS4-BAL], 0) > 0
)
AND I4.[PA-INS-CO-CD] IN ('C','J','G','M','N','O','P','Y')
AND I4.[PA-LAST-INS-PAY-DATE] IS NULL
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)

UNION ALL

SELECT DISTINCT [track_id] = '12758',
	[spol_group] = 'Group_4',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I4 ON PD.[PA-PT-NO-WOSCD] = I4.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I4.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND I3.[PA-INS-CO-CD] = 'C'
AND I3.[PA-INS-PLAN-NO] = '49'
AND I4.[PA-INS-CO-CD] = 'P'
AND I4.[PA-INS-PLAN-NO] = '12'
AND (
	ISNULL(I4.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS4-BAL], 0) > 0
)
AND I3.[PA-INS-SUBSCR-INS-GROUP-ID] = I4.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS Z
	WHERE PD.[PA-PT-NO-WOSCD] = Z.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = Z.[PA-PT-NO-SCD-1]
	AND Z.[PA-DTL-SVC-CD-WOSCD] = '50399'
)
AND (
	(
		I3.[PA-LAST-INS-PAY-DATE] IS NOT NULL
		OR EXISTS (
			SELECT 1
			FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DetailInformation AS DI
			WHERE DI.[PA-PT-NO-WOSCD] = PD.[PA-PT-NO-WOSCD]
			AND DI.[PA-PT-NO-SCD-1] = PD.[PA-PT-NO-SCD-1]
			AND DI.[PA-DTL-SVC-CD-WOSCD] IN ('3816604','3816603')
			AND DI.[PA-DTL-POST-DATE] BETWEEN DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
		)
	)
)

UNION ALL

SELECT DISTINCT [track_id] = '12758',
	[spol_group] = 'Group_5',
	[pt_no] = CAST(PD.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(PD.[PA-PT-NO-SCD-1] AS VARCHAR)
FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.PatientDemographics AS PD
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I1 ON PD.[PA-PT-NO-WOSCD] = I1.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I1.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '1'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I2 ON PD.[PA-PT-NO-WOSCD] = I2.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I2.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '2'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I3 ON PD.[PA-PT-NO-WOSCD] = I3.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I3.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '3'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.InsuranceInformation AS I4 ON PD.[PA-PT-NO-WOSCD] = I4.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = I4.[PA-PT-NO-SCD-1]
	AND I1.[PA-INS-PRTY] = '4'
LEFT JOIN [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.UnitizedAccounts AS UA ON PD.[PA-PT-NO-WOSCD] = UA.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = UA.[PA-PT-NO-SCD-1]
WHERE PD.[PA-UNIT-STS] != 'U'
AND (
	ISNULL(I4.[PA-BAL-INS-PROR-NET-AMT], 0) > 0
	OR ISNULL(UA.[PA-UNIT-INS4-BAL], 0) > 0
)
AND I3.[PA-INS-SUBSCR-INS-GROUP-ID] = I4.[PA-INS-POL-NO]
AND NOT EXISTS (
	SELECT 1
	FROM [ECHOLOADERDBP.UHMC.SBUH.STONYBROOK.EDU].echo_active.dbo.DETAILINFORMATION AS DI
	WHERE PD.[PA-PT-NO-WOSCD] = DI.[PA-PT-NO-WOSCD]
	AND PD.[PA-PT-NO-SCD-1] = DI.[PA-PT-NO-SCD-1]
	AND DI.[PA-DTL-SVC-CD-WOSCD] = '80107'
	AND DI.[PA-DTL-INS-CD] = '244'
	AND DI.[PA-DTL-POST-DATE] BETWEEN DATEADD(DAY, -22, CAST(GETDATE() AS DATE)) AND DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
)