WITH CTE AS (
    SELECT DISTINCT PATIENT_CONTROL_NUMBER,
        Ins_CD,
        CLAIM_STATUS,
        BILL_TYPE,
        CHECK_EFT_DATE,
        PAYER_NAME,
        CROSSOVER_CARRIER,
        LINE_ADJUSTMENT_GROUP_CODE,
        LINE_ADJUSTMENT_REASON_CODE
    FROM SMS.DBO.c_remit_JOIN_ALL_TBL
    WHERE CHECK_EFT_DATE >= '2026-01-01'
    AND CHECK_EFT_DATE < '2026-07-01'
    AND PARENT_NAME = 'Stony Brook University Hospital'
),

PR AS (
    SELECT CTE.Patient_Control_Number,
        CTE.Ins_CD,
        CTE.CLAIM_STATUS,
        CTE.BILL_TYPE,
        CTE.CHECK_EFT_DATE,
        PAYER_NAME = CTE.PAYER_NAME,
        CROSSOVER_CARRIER = CTE.CROSSOVER_CARRIER,
        CTE.LINE_ADJUSTMENT_GROUP_CODE,
        CTE.LINE_ADJUSTMENT_REASON_CODE,
        [PR_INDICATOR] = CASE 
            WHEN CTE.LINE_ADJUSTMENT_GROUP_CODE = 'PR' 
            AND CTE.LINE_ADJUSTMENT_REASON_CODE NOT IN ('1', '2', '3')
                THEN 1
            ELSE 0
        END
    FROM CTE AS CTE
)

--CARC_RARC_CD AS (
    SELECT [PATIENT_CONTROL_NUMBER] = PR.Patient_Control_Number,
        [INS_CD] = PR.Ins_CD,
        [CLAIM_STATUS] = PR.CLAIM_STATUS,
        [BILL_TYPE] = PR.BILL_TYPE,
        [CHECK_EFT_DATE] = PR.CHECK_EFT_DATE,
        [PAYER_NAME] = PR.PAYER_NAME,
        [CROSSOVER_CARRIER] = PR.CROSSOVER_CARRIER,
        [CARC_RARC_CODE] = CAST(PR.LINE_ADJUSTMENT_GROUP_CODE AS VARCHAR(5)) + CAST(PR.LINE_ADJUSTMENT_REASON_CODE AS VARCHAR(5)),
        [LINE_ADJUSTMENT_GROUP_CODE] = PR.LINE_ADJUSTMENT_GROUP_CODE,
        [LINE_ADJUSTMENT_REASON_CODE] = PR.LINE_ADJUSTMENT_REASON_CODE,
        [PR_INDICATOR] = PR.PR_INDICATOR
    FROM PR AS PR
    -- MUST HAVE ACCOUNTS WITH A PR INDICATOR
    WHERE EXISTS (
        SELECT 1
        FROM PR AS ZZZ
        WHERE ZZZ.Patient_Control_Number = PR.Patient_Control_Number
        AND ZZZ.PR_INDICATOR = 1
    )
    --AND PR.Patient_Control_Number = '01025904628100B14003'
    AND CAST(PR.LINE_ADJUSTMENT_GROUP_CODE AS VARCHAR(5)) + CAST(PR.LINE_ADJUSTMENT_REASON_CODE AS VARCHAR(5)) NOT IN ('PR1', 'PR2', 'PR3')
--)
--SELECT top 10 A.Patient_Control_Number,
--    A.Ins_CD, A.CLAIM_STATUS,
--    A.BILL_TYPE,
--    COMBINED_CARC_RARC_CODE = STRING_AGG(A.CARC_RARC_CODE, ', ')
--FROM CARC_RARC_CD AS A
--GROUP BY A.Patient_Control_Number, A.Ins_CD, A.CLAIM_STATUS, A.BILL_TYPE
