USE [DSH]

SELECT DISTINCT B340.[PA-PT-NO-WOSCD],
	B340.[PA-PT-NO-SCD],
	CAST(B340.[PA-PT-NO-WOSCD] AS VARCHAR) + CAST(B340.[PA-PT-NO-SCD] AS VARCHAR) AS [PT-NO],
	B340.[admit_date],
	B340.[dsch_date],
	B340.[TYPE],
	--COSTS.[TYPE],
	INS.[PA-INS-PLAN],
	INS.[PA-INS-PRTY],
	B340.[PA-UNIT-NO],
	COSTS.[PA-DTL-REV-CD],
	COSTS.[Adjusted Rev Code],
	COSTS.[Rev Code from CDM],
	B340.[PA-DTL-SVC-CD],
	B340.[PA-DTL-UNIT-DATE],
	B340.[340B-IND],
	B340.[REPORTING-GROUP],
	B340.[TOT-CHG-QTY],
	ISNULL(COSTS.[SUM OF TOT PROF FEES], 0) AS [SUM OF TOT PROF FEES],
	ISNULL(COSTS.[SUM OF TOT CHG], 0) AS [SUM OF TOT CHG],
	ISNULL(COSTS.[SUM_OF_CHARGESAND_PROF_FEES], 0) AS [SUM_OF_CHARGESAND_PROF_FEES]
FROM [DSH].[DBO].[2016_340B_INDICATOR] AS B340
LEFT JOIN [dbo].[2016_DSH_Costs] AS COSTS ON B340.[PA-PT-NO-WOSCD] = COSTS.[pa-pt-no-woscd]
	AND B340.[PA-PT-NO-SCD] = COSTS.[PA-PT-NO-SCD]
	AND B340.[PA-UNIT-NO] = COSTS.[PA-UNIT-NO]
	AND B340.[PA-DTL-SVC-CD] = COSTS.[PA-DTL-SVC-CD]
	AND B340.[PA-DTL-UNIT-DATE] = COSTS.[UNIT-DATE]
LEFT JOIN [dbo].[CUSTOMINSURANCE] AS INS ON B340.[PA-PT-NO-WOSCD] = INS.[pa-pt-no-woscd]
	AND B340.[PA-PT-NO-SCD] = INS.[PA-PT-NO-SCD]
--WHERE [REPORTING-GROUP] IN (
--      'PRIMARY MEDICAID',
--      'PRIMARY MEDICAID MANAGED CARE',
--      'MEDICAID FFS DUAL ELIGIBLE',
--      'MEDICAID MANAGED CARE DUAL ELIGIBLE',
--      'PRIMARY OUT OF STATE MEDICAID'
--     ,'DUAL ELIGIBLE OUT OF STATE MEDICAID'
--      )
WHERE [PA-INS-PRTY] = '1'
	AND [PA-INS-PLAN] IN ('D98', 'D99', 'U01', 'U02', 'U04', 'U05', 'U23', 'U27', 'U31', 'U34', 'U42', 'U57');
