SELECT *
INTO #TEMPA
FROM [dbo].[DSH_INSURANCE_TABLE_W_REPORT_GROUPS]
WHERE (
		[PRIMARY-TYPE] = 'PRIMARY MEDICARE'
		AND (
			[2NDRY-MEDICAID-FFS] != '0'
			OR [2NDRY-MEDICAID-ELIGIBLE] != '0'
			OR [2NDRY-MEDICAID-PENDING-IND] != '0'
			OR [2NDRY-MEDICAID-OUT-OF-STATE-IND] != '0'
			)
		)
AND [DENIAL-IND] = '0'
;

SELECT TOP 1 *
FROM #TEMPA;

-----

SELECT [PA-PT-NO-WOSCD],
	[PA-PT-NO-SCD],
	[PT-NO],
	[PA-UNIT-NO],
	CASE 
		WHEN [PA-UNIT-NO] IS NULL
			THEN NULL
		ELSE CAST([PA-DTL-UNIT-DATE] AS DATE)
		END AS [PA-DTL-UNIT-DATE]
	, SUM([TOT-PAYMENTS]) AS [TOTAL-PAYMENTS]
--, [tot-payments]
INTO #TEMPB
FROM [DSH].[dbo].[2016_DSH_Payments] AS A
WHERE LTRIM(RTRIM([PA-DTL-SVC-CD])) = '108084'
--AND [PT-NO] = '10104478713'
--AND [PA-UNIT-NO] IS NOT NULL
GROUP BY [PA-PT-NO-WOSCD],
	[PA-PT-NO-SCD],
	[PT-NO],
	[PA-UNIT-NO],
	[PA-DTL-UNIT-DATE],
	[PA-DTL-SVC-CD];
;

-----

SELECT a.[PA-PT-NO-WOSCD],
	a.[PA-PT-NO-SCD],
	CASE 
		WHEN a.[pa-acct-type] IN ('1', '2', '4', '8')
			THEN 'IP'
		WHEN A.[pa-acct-type] IN ('0', '6', '7')
			THEN 'OP'
		ELSE 'OTHER'
		END AS [TYPE],
	SUM(ISNULL(A.[TOT-INS-PAYMTS], 0)) AS [TOT-MEDICARE-PRIM-MEDICAID-SECONDARY],
	SUM(ISNULL(B.[TOTAL-PAYMENTS], 0)) AS [TOT-MEDICAID-SECONDARY-PAYMENTS]
INTO #TEMPC
FROM #TEMPA AS A
LEFT OUTER JOIN #TEMPB AS B ON A.[PA-PT-NO-WOSCD] = B.[PA-PT-NO-WOSCD]
	AND A.[PA-PT-NO-SCD] = B.[PA-PT-NO-SCD]
GROUP BY A.[PA-PT-NO-WOSCD],
	A.[PA-PT-NO-SCD],
	a.[pa-acct-type];

-----

SELECT *
FROM #TEMPC;

-----

DROP TABLE #TEMPA;

DROP TABLE #TEMPB;

DROP TABLE #TEMPC;
