SELECT COSTS.[pa-pt-no-woscd],
	COSTS.[PA-PT-NO-SCD],
	CAST(COSTS.[pa-pt-no-woscd] AS VARCHAR) + CAST(COSTS.[PA-PT-NO-SCD] AS VARCHAR) AS [PT-NO],
	COSTS.[PA-UNIT-NO],
	ENC.admit_date,
	COSTS.[PA-DTL-REV-CD],
	COSTS.[Adjusted Rev Code],
	COSTS.[Rev Code from CDM],
	B340.[PA-DTL-SVC-CD],
	B340.[PA-DTL-UNIT-DATE],
	ENC.[ptacct_type],
	B340.[340B-IND],
	COSTS.[REPORTING GROUP],
	B340.[TOT-CHG-QTY],
	B340.[Total Charges including Prof Fees],
	COSTS.[SUM OF TOT PROF FEES],
	COSTS.[SUM OF TOT CHG]
FROM [dbo].[2016_DSH_Costs] AS COSTS
LEFT OUTER JOIN [DBO].[2016_340B_INDICATOR] AS B340 ON COSTS.[pa-pt-no-woscd] = B340.[PA-PT-NO-WOSCD]
	AND COSTS.[PA-PT-NO-SCD] = B340.[PA-PT-NO-SCD]
	AND COSTS.[PA-UNIT-NO] = B340.[PA-UNIT-NO]
	AND COSTS.[PA-DTL-SVC-CD] = B340.[PA-DTL-SVC-CD]
LEFT OUTER JOIN [dbo].[Encounters_For_DSH] AS ENC ON COSTS.[pa-pt-no-woscd] = ENC.[PA-PT-NO-WOSCD]
	AND COSTS.[PA-PT-NO-SCD] = ENC.[PA-PT-NO-SCD]
	AND COSTS.[PA-UNIT-NO] = ENC.[pa-unit-no]
	--WHERE COSTS.[PA-PT-NO-WOSCD] = '1008416365'
	--AND COSTS.[PA-PT-NO-SCD] = '7'
	--;
