/*
Author: Steven Sanderson, MPH - Manchu Technologies Corp
*/

SELECT CAST(PMTS.[PA-PT-NO-WOSCD] AS VARCHAR) AS [PA-PT-NO-WOSCD],
	CAST(PMTS.[PA-PT-NO-SCD] AS VARCHAR) AS [PA-PT-NO-SCD],
	CAST(PMTS.[PT-NO] AS VARCHAR) AS [PT-NO],
	CAST(PMTS.[PA-UNIT-NO] AS VARCHAR) AS [PA-UNIT-NO],
	CAST(PMTS.[unit-date] AS VARCHAR) AS [UNIT-DATE],
	CAST(PMTS.[PA-DTL-UNIT-DATE] AS VARCHAR) AS [PA-DTL-UNIT-DATE],
	CAST(PMTS.[TYPE] AS VARCHAR) AS [TYPE],
	CAST(PMTS.[PA-DTL-TYPE-IND] AS VARCHAR) AS [PA-DTL-TYPE-IND],
	CAST(PMTS.[PA-DTL-GL-NO] AS VARCHAR) AS [PA-DTL-GL-NO],
	CAST(PMTS.[PA-DTL-SVC-CD] AS VARCHAR) AS [PA-DTL-SVC-CD],
	CAST(PMTS.[PA-DTL-CDM-DESCRIPTION] AS VARCHAR) AS [PA-DTL-CDM-DESCRIPTION],
	CAST(PMTS.[PA-UNIT-STS] AS VARCHAR) AS [PA-UNIT-STS],
	CAST(PMTS.[REPORTING GROUP] AS VARCHAR) AS [REPORTING-GROUP],
	CAST(PMTS.[TOT-PAYMENTS] AS VARCHAR) AS [TOT-PAYMENTS]
FROM [DBO].[2016_DSH_PAYMENTS] AS PMTS

UNION ALL

SELECT CAST(MFA1.[PA-PT-NO-WOSCD] AS VARCHAR) AS [PA-PT-NO-WOSCD],
	CAST(MFA1.[PA-PT-NO-SCD] AS VARCHAR) AS [PA-PT-NO-SCD],
	'' AS [PT-NO],
	'' AS [PA-UNIT-NO],
	'' AS [UNIT-DATE],
	'' AS [PA-DTL-UNIT-DATE],
	CAST(MFA1.[TYPE] AS VARCHAR) AS [TYPE],
	CAST(MFA1.[PA-DTL-TYPE-IND] AS VARCHAR) AS [PA-DTL-TYPE-IND],
	'' AS [PA-DTL-GL-NO],
	'' AS [PAT-DTL-SVC-CD],
	CAST(MFA1.[PA-DTL-CDM-DESCRIPTION] AS VARCHAR) AS [PA-DTL-CDM-DESCRIPTION],
	'' AS [PA-UNIT-STS],
	CAST(MFA1.[REPORTING-GROUP] AS VARCHAR) AS [REPORTING-GROUP],
	CAST(MFA1.[TOT-PAYMENTS] AS VARCHAR) AS [TOT-PAYMENTS]
FROM [dbo].[DSH_Main_File_Adjustments] AS MFA1
WHERE DATEPART(YEAR, MFA1.[ADMIT_DATE]) = '2016'
